<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.1//EN" "http://www.w3.org/TR/xhtml11/DTD/xhtml11.dtd">
	<html xmlns="http://www.w3.org/1999/xhtml">
	<head>

		<title>Comet</title>
		<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
		<script type="text/javascript">
			function CometBroadcast(data, origin, packetId) {
				origin = origin || "*";
				var wrapped = {
					url: window.location.pathname + window.location.search,
					data: data
				};
				var packetNode = document.getElementById('comet-packet-' + packetId);
				packetNode.parentNode.removeChild(packetNode);
				window.parent.postMessage(wrapped, origin);
			}
		</script>
	</head>
	<body>
