<div id="ERROR-PAGE">
  <div class="header">A transaction error has occurred.</div>
  <div class="info">
    This transaction has been logged and the operator notified for manual processing.
  </div>
  <div class="email-address">
    <input type="text" id="email-address" />
  </div>
  <div class="instructions">
    You may enter your email address so that the operator may notify you when this issue is resolved.
  </div>
  <div class="btn-large-info" id="btn-error-done">Done</div>
</div>
