<div id="HELP-PAGE">
  <div class="header">
    <div class="btn-back">
      <img src="/assets/images/btn-back.png" width="75" height="75" />
    </div>
    Bitcoin ATM Help
  </div>

  <!-- TODO: programatically render QandA rather than hardcoding into HTML -->
  <div class="main-box">
    <div class="qa-box">
      <div class="question">What is bitcoin?</div>
      <div class="answer">
      Bitcoin is an open-source decentralized protocol. It is also a unit of account within that protocol. 
      <br /><br />
      Learn more at bitcoin.org
      </div>
    </div>

    <div class="qa-box">
      <div class="question">How do I use this vending machine?</div>
      <div class="answer">
        <b>New Users of Bitcoin</b>
        <ol>
          <li>Go to https://blockchain.info/wallet/new on your smartphone and set up a new bitcoin wallet.</li>
          <li>After creating a new wallet and logging in, you'll see the QR code of your default bitcoin address under the "Wallet Home" section of your app.</li>
          <li>Scan your QR code into Skyhook and verify that the addresses match by selecting YES when prompted.</li>
          <li>Insert Cash</li>
          <li>Buy Bitcoins</li>
        </ol>
        <b>Existing Users of Bitcoin</b>

        <ol>
          <li>Scan Your QR Code</li>
          <li>Insert Cash</li>
          <li>Buy Bitcoins</li>
        </ol>
      </div>
    </div>

    <div class="qa-box">
      <div class="question">How do I get a bitcoin wallet?</div>
      <div class="answer">
        While there are several options available, but we recommend blockchain.info's online wallet for new users.
        <br /><br />
        Additionally we encourage Skyhook operators to offer bitcoin wallet solutions for new bitcoin users.
      </div>
    </div>

    <div class="qa-box">
      <div class="question">What is a QR code?</div>
      <div class="answer">
        QR or "Quick Response" codes are machine-readable codes consisting of a grid of black and white squares, typically used for storing URLs or other information for use on a smartphone.
      </div>
    </div>

    <div class="qa-box">
      <div class="question">How do I display my bitcoin address as a QR code?</div>
      <div class="answer">
        After logging in to https://blockchain.info/wallet, you'll see the QR code for your default bitcoin address on the "Wallet Home" page.
        <br /><br />
        If you are using a wallet that doesn't support QR code generation you can copy your public bitcoin address and paste it into the following website in order to generate a QR code. 
        <br /><br />
        http://bitcoinqrcode.org/
      </div>
    </div>

    <div class="qa-box">
      <div class="question">Is it safe?</div>
      <div class="answer">
        While the bitcoin protocol is safe and secure, incorrect use of a wallet may result in your bitcoins being lost or stolen. In order to understand how to properly secure your coins, please visit the website below. 
        <br /><br />
        http://bitcoin.org/en/you-need-to-know  
      </div>
    </div>

    <div class="qa-box">
      <div class="question">What can I buy with bitcoins?</div>
      <div class="answer">Here's an article on the subject. http://btcpdx.com/buy</div>
    </div>
  </div>
</div>
