<div id="DEPOSIT-PAGE">
  <div class="instructions">Insert a bill</div>
  <div class="low-funds-warning"><b>Bitcoin funds low:</b> Do not insert bills larger than <b id="low-funds-amount"></b></div>
  <div class="no-funds-error"><b>Bitcoin funds empty:</b> Do not insert any more bills.</div>
  <div class="totals-box">
    <div class="cash-deposited-label">cash deposited</div>
    <div class="cash-deposited"><b id="cash-deposited-amount">$0</b> CAD</div>
    <div class="divider">&#8659;</div>
    <div class="bitcoin-purchased-label">bitcoin purchased</div>
    <div class="bitcoin-purchased"><b id="bitcoin-purchased-amount">0.00000000</b> BTC</div>
  </div>
  <div class="bitcoin-sent-to-label">Bitcoin will be sent to:</div>
  <div class="bitcoin-sent-to"></div>
  <div class="btn-large-fail hidden" id="btn-buy-cancel">Cancel</div>
  <div class="btn-large-success hidden" id="btn-send-bitcoin">Send Bitcoin</div>
</div>
