<div id="DEPOSIT-PAGE">
  <div class="instructions">Insert a bill</div>
  <div class="low-funds-warning">Bitcoin funds low: Do not insert bills larger than ...</div>
  <div class="no-funds-error">Bitcoin funds empty: Do not insert any more bills.</div>
  <div class="totals-box">
    <div class="cash-deposited-label">cash deposited</div>
    <div class="cash-deposited"><b id="cash-deposited-value">$0</b> <span class="cash-deposited-currency">CAD</span></div>
    <div class="divider">&#8659;</div>
    <div class="bitcoin-purchased-label">bitcoin purchased</div>
    <div class="bitcoin-purchased"><b id="bitcoin-purchased-value">0.00000000</b> BTC</div>
  </div>
  <div class="bitcoin-sent-to-label">Bitcoin will be sent to:</div>
  <div class="bitcoin-sent-to"></div>
  <div class="btn-large-fail hidden" id="btn-buy-cancel">Cancel</div>
  <div class="btn-large-success hidden" id="btn-send-bitcoin">Send Bitcoin</div>
</div>
