<?php
$title = 'Project Skyhook';
$styles = [
	'/assets/Messi/messi.css',
	'/assets/css/skyhook.css',
];
$currencyMeta = $config->getCurrencyMeta();
$classes = ['receipt'];
include 'head.phtml';
?>
<div id="help-panel">
	<?= file_get_contents(Localization::path("help.html")); ?>
	<a href="#" class="closer button">&times;</a>
</div>
<div class="receipt-content">
	<h3>
		<?= $i18n->_('transaction complete') ?>
	</h1>
	<p>
		<?= $i18n->_('Bitcoin Address:') ?>
		<strong class="address"><?= $purchase->getCustomerAddress()->get() ?></strong> <br /> <br />
		<?= $i18n->_('has been sent:')?>
		<strong class="total"><?= $purchase->getBitcoinAmount()->get() ?> <?= $i18n->_('BTC') ?></strong> <br />
		<?= $i18n->_('for the price of:') ?>
		<strong class="total"><?= $currencyMeta->format($purchase->getCurrencyAmount(), false) ?> <?= $currencyMeta->getISOCode() ?></strong>
	</p>
	<div id="email-receipt">
		<? if (!$sent): ?>
		<form
			action="/email-receipt"
			method="POST"
			autocomplete="off"
		>
			<input type="hidden" name="ticket" value="<?= $purchase->getId() ?>" />
			<div>
				<input type="email" name="email" id="email" />
			</div>
			<div class="button-wrapper">
				<input type="submit" value="<?= $i18n->_('email me a receipt') ?>" />
			</div>
			<? if ($error): ?>
			<div class="error">
				<?= $i18n->_('Invalid Email') ?>
			</div>
			<? endif; ?>
		</form>
		<? else: ?>
		<div id="sent">
			<?= $i18n->_('Email Sent') ?>
		</div>
		<? endif; ?>
	</div>
	<div class="button-wrapper">
		<a href="/start" class="button">
			<?= $i18n->_('done') ?>
		</a>
	</div>
</div>
<div id="footer">
	<a href="" id="help" class="button">?</a>
</div>
<?php
$scripts = [
	'/assets/gettext/Gettext.js',
	'/assets/jQuery/jquery.min.js',
	'/assets/js/helper.js',
	'/assets/Messi/messi.min.js',
	'/assets/js/HelpPanel.js',
	'/assets/js/timeout.js',
];
include 'foot.phtml';
