<div id="START-PAGE">
  <div class="options-box">
    <img id="btn-help" src="assets/images/help-icon.png" width="75" height="75" />
    <img id="btn-lang" src="assets/images/lang-icon.png" width="75" height="75" />
  </div>
  <img class="bitcoin-logo" src="/assets/images/bitcoin.png" width="300" height="300" />
  <div class="bitcoin-atm">Bitcoin ATM</div>
  <div class="btn-large-success" id="btn-buy-bitcoin">Buy some Bitcoin</div>
</div>
