<!-- Admin Password -->
<div id="password-settings" data-role="collapsible" data-collapsed="true">
	<div id="password-error">
	</div>
	<h3>
		<?= $i18n->_('Password Settings')?>
	</h3>
	<label for="admin_password">
		<?= $i18n->_('Set or Change Operator Password:')?>
	</label>
	<input
		type="password"
		name="admin_password"
		id="admin_password"
		value="<?= $html->escape($password); ?>"
	/>
	<label for="confirm_admin_password">
		<?= $i18n->_('Confirm New Password:')?>
	</label>
	<input
		type="password"
		name="confirm_admin_password"
		id="confirm_admin_password"
		value="<?= $html->escape($password); ?>"
	/>
</div><!-- /Admin Password -->
