<!-- Device Commands -->
<div id="device-commands" data-role="collapsible" data-collapsed="true">
	<h3><?= $i18n->_('Device Commands') ?></h3>
	<input
		id="restart-machine"
		type="button"
		data-inline="true"
		disabled="disabled"
		value="<?= $i18n->_('Restart Machine') ?>"
	/>
	<input
		id="restart-services"
		type="button"
		data-inline="true"
		disabled="disabled"
		value="<?= $i18n->_('Restart Services') ?>"
	/>
	<input
		id="restart-firefox"
		type="button"
		data-inline="true"
		value="<?= $i18n->_('Crash Browser') ?>"
	/>
</div><!-- /Device Commands -->
