<?
$locale = Localization::getLocale();
?>
<!-- Locale Settings -->
<div id="locale-settings" data-role="collapsible" data-collapsed="true">
	<h3>
		<?= $i18n->_('Localization Settings')?>
	</h3>
	<div id="locale-errors"></div>
	<div data-role="fieldcontain">
		<label for="locale">
			<?= $i18n->_('Localize for:')?>
		</label>
		<select
			name="locale"
			id="locale"
			data-theme="a"
			data-native-menu="false"
		>
		<? foreach(Localization::getAvailableLocales() as $v): ?>
			<option
				value="<?= $html->escape($v['locale_name']) ?>"
				<? if ($locale === $v['locale_name']): ?>
				selected="selected"
				<? endif; ?>
			>
				<?= $html->escape($v['label']) ?>
			</option>
		<? endforeach; ?>
		</select>
	</div>
</div><!-- /Locale -->
